baseURL: /
title: Evil 2 the Core
theme: hugo-theme-bootstrap
copyright: 'Copyright Â© 1995-{year} Syncriix. All Rights Reserved.'
defaultContentLanguage: en
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
defaultContentLanguageInSubdir: false
disableLanguages:
- fr
- ja
- js
- ar
- zh-cn
- zh-tw
- zh-hans
- zh-hant
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname
refLinksErrorLevel: WARNING 

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

enableGitInfo: true
repo.url: https://github.com/Syncriix/hugo-theme-bootstrap-skeleton


permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

module:
  imports:
    - path: github.com/razonyang/hugo-theme-bootstrap
#   proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
