baseURL: /
title: Evil 2 the Core
theme: hugo-theme-bootstrap
copyright: 'Copyright Â© 1995-{year} Syncriix. All Rights Reserved.'
defaultContentLanguage: en
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

# module:
  # proxy: https://goproxy.cn
